sudo: required
dist: trusty

before_install:
 - chmod +x gradlew

language: java
jdk:
- openjdk8
- oraclejdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

env: GRADLE_OPTS="-Xms1g -Xmx3g"
script: ./gradlew build


notifications:
  email: false

deploy:
  file_glob: true
  provider: releases
  api-key: ${KEY}
  file: "./build/libs/I.N. | Statistics*.jar"
  skip_cleanup: true
  on:
    tags: true
